version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - type: bind
        source: /root/.acme.sh/malal.fun
        target: /certs
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:8.0
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Pomme123;
    volumes:
      - type: volume
        source: dbprod
        target: /var/lib/mysql

  fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - type: volume
        target: /app/vendor    
      - type: bind
        source: .
        target: /app
  node:
    build:
      context: .
      dockerfile: Dockerfile.webpack.prod      
    volumes:
      - type: volume
        target: /app/node_modules
      - type: bind
        source: .
        target: /app

volumes:
  dbprod: